-- This file is kept as a human-readable snapshot only.
-- Prefer applying migrations under `supabase/migrations/`.
--
-- Latest migration:
-- - `supabase/migrations/20260410_000001_shopify_like_admin.sql`